### ISSUE TITLE
Compatibility with NVDA 2023.1

### ISSUE THREAD

**Issue by legle** [mltony/nvda-indent-nav#14]
Hello! Are you planing to add compability with NVDA 2023.1?

It is a very nice add-on for software engineers productivity and I do not want to lost this functionality

**Comment by mltony** [comment]
I will update it eventually. Probably towards the end of the year.

**Comment by legle** [comment]
Hello, any thing about this problem? I really like to use this add-on.

**Comment by mltony** [comment]
Current IndentNav release should be compatible with 2023. In the next few months I'll make it compatible with 2024 and upload to addon store.

**Comment by Neurrone** [comment]
2024.1 would be great, I believe it will be coming out soon if nothing is found in the RC.

**Comment by mltony** [comment]
I am working on the next version of Indent nav right now. Will be compatible with 2024. I'll make a new release probably within a month.

**Comment by cary-rowen** [comment]
Is this add-on ready?

**Comment by cary-rowen** [comment]
@mltony 
This is done, we can close it

**Comment by mltony** [comment]
IndentNav v2.0 is now compatible with NVDA v2023 and v2024 series.
