### ISSUE TITLE
Request an update to the add-on template

### ISSUE THREAD

**Issue by cary-rowen** [mltony/nvda-indent-nav#15]
Hi @mltony 

Currently this add-on is still using the old add-on template.

This caused an issue where the tables in the document were not being rendered correctly.

Of course we can have other ways of rendering the table, but I think using an add-on template is a more suitable option.
Using add-on templates you can also use github actions to publish add-on.

If you don't have time to do this right now, I'd be happy to help.

Btw, @nvdaes has helped register the add-on with the translation system. If you wish, you can grant me access to this repository and I will be willing to provide localization management.

Thanks
Cary

**Comment by mltony** [comment]
@nvdaes, 
thank you for helping with translation system, please also grant full access to @cary-rowen. 

@cary-rowen ,
I just granted you access  to this repo. Updating addon template sounds like a good idea!

**Comment by cary-rowen** [comment]
@mltony 
I will take the time to update the add-on template.

@nvdaes 
Thanks for your efforts on this, and as Tony said, I'd like to have access to nvdaaddons/indent-nav as well.

I will also take the time to update sentence-nav. If possible, please also ask @nvdaes to help me check the access of nvdaaddons/sentence-nav.

Thanks a lot!

**Comment by mltony** [comment]
@nvdaes, IJ confirm, could you also grant access to @cary-rowen for nvda-sentence-nav? Thanks!

**Comment by nvdaes** [comment]
Hello, now @cary-rowen has access to sentenceNav and IndentNav.
