### ISSUE TITLE
Please add a stable branch for translations

### ISSUE THREAD

**Issue by feerrenrut** [mltony/nvda-indent-nav#5]
For translations a 'stable' branch is required, see https://github.com/nvaccess/mrconfig#translating-your-addon

This branch must also be available from https://github.com/nvdaaddons/IndentNav

**Comment by mltony** [comment]
Thanks for advice, will work on that on the weekend.

**Comment by mltony** [comment]
@feerrenrut, I added stable branch to my repo, but I don't appear to have write access to https://github.com/nvdaaddons/IndentNav to add stable branch there. How can I get access?

**Comment by mltony** [comment]
Ok, I figured out access rights with translation team and pushed stable branch to nvdaaddons. I think this add-on is in correct state for translation workflow now. I'll close this for now, but feel free to reopen if I am still missing anything.
