### ISSUE TITLE
Ignore blank lines containing indentation

### ISSUE THREAD

**Issue by TheQuinbox** [mltony/nvda-indent-nav#6]
Some programmers put blank lines between their functions, but with whitespace on the lines. I have no idea why, but nonetheless it's extremely annoying to go through with indent nav. It would be awesome if you could make it so blank lines containing only indentation are ignored the same way standard blank lines are.

**Comment by mltony** [comment]
Blank lines are indeed ignored. Please provide step-by-step instructions 
on how to reproduce with a concrete example.

**Comment by TheQuinbox** [comment]
After doing a bit of testing, it only seems to happen if a blank line contains a tab. Download https://www.dropbox.com/s/0tulmvd8ix9ox9e/test.py?dl=1. Attempt to navigate between functions with indent nav.

**Comment by mltony** [comment]
Ah, right, it doesn't work well with tabs. I took a note - will try to 
fix that whenever I have time.

**Comment by TheQuinbox** [comment]
If nvaccess/nvda#14102 gets merged, this issue should be closed. That PR makes speech.isBlank also detect \t as a blank character.

**Comment by TheQuinbox** [comment]
That's a no, but when I have a free weekend I'll tackle this issue. Shouldn't be too difficult.
